# Generated by Django 4.2.11 on 2024-07-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAvatar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatarState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyAvatar.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_potato',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_goal',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('hat', 'Hat'), ('clothes', 'Clothes'), ('accessory', 'Accessory'), ('background', 'Background')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AddField(
            model_name='useritem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserItem_ItemId', to='MyAvatar.item'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserItem_UserId', to='MyAvatar.user'),
        ),
        migrations.AddField(
            model_name='useravatarstate',
            name='accessory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_user', to='MyAvatar.item'),
        ),
        migrations.AddField(
            model_name='useravatarstate',
            name='background_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_user', to='MyAvatar.item'),
        ),
        migrations.AddField(
            model_name='useravatarstate',
            name='clothes_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes_user', to='MyAvatar.item'),
        ),
        migrations.AddField(
            model_name='useravatarstate',
            name='hat_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hat_user', to='MyAvatar.item'),
        ),
    ]
