# Generated by Django 4.2.11 on 2024-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAvatar', '0002_useravatarstate_useritem_remove_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_potato',
            field=models.IntegerField(default=0),
        ),
    ]
