# Generated by Django 4.2.11 on 2024-07-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAvatar', '0003_user_current_potato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_potato',
        ),
    ]
