# Generated by Django 5.0.6 on 2024-07-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_author_last_name'),
        ('test_app', '0006_alter_author_first_name'),
    ]

    operations = [
    ]
