# Generated by Django 4.2.13 on 2024-07-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_author_last_name'),
        ('test_app', '0006_alter_author_first_name'),
    ]

    operations = [
    ]
